create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) null, `email` varchar(255) not null, `device_id` varchar(255) null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
alter table `users` add unique `users_email_unique`(`email`)
create table `books` (`id` int unsigned not null auto_increment primary key, `title` varchar(255) not null, `description` text null, `link` varchar(255) null, `img` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `authors` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `surname` varchar(255) not null, `title` varchar(255) not null, `img` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `author_book` (`id` bigint unsigned not null auto_increment primary key, `author_id` int unsigned not null, `book_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `sections` (`id` bigint unsigned not null auto_increment primary key, `title` varchar(255) not null, `type` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `book_section` (`id` bigint unsigned not null auto_increment primary key, `book_id` int unsigned not null, `section_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `author_section` (`id` bigint unsigned not null auto_increment primary key, `author_id` int unsigned not null, `section_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `tests` (`id` bigint unsigned not null auto_increment primary key, `title` varchar(255) not null, `img` varchar(255) not null default '', `progress` int not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `questions` (`id` bigint unsigned not null auto_increment primary key, `question` text not null, `type` varchar(255) not null, `test_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
alter table `questions` add constraint `questions_test_id_foreign` foreign key (`test_id`) references `tests` (`id`) on delete cascade
create table `answers` (`id` bigint unsigned not null auto_increment primary key, `answer` text not null, `is_correct` tinyint(1) not null default '0', `question_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
alter table `answers` add constraint `answers_question_id_foreign` foreign key (`question_id`) references `questions` (`id`) on delete cascade
create table `section_test` (`id` bigint unsigned not null auto_increment primary key, `test_id` int unsigned not null, `section_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'
create table `book_user` (`user_id` int unsigned not null, `book_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci'